driver=nl80211
interface=wlan0

ssid=Rowe Farm
utf8_ssid=1

country_code=GB
hw_mode=g
ieee80211d=1
preamble=1
uapsd_advertisement_enabled=1

ap_isolate=1
bridge=br0
bridge_hairpin=1
multicast_to_unicast=1
wds_sta=1

ieee80211n=1
ht_capab=[LDPC][SHORT-GI-20][TX-STBC][RX-STBC1][MAX-AMSDU-7935]

ieee80211ax=1
he_bss_color=17
he_su_beamformer=1
he_su_beamformee=1
he_mu_beamformer=1

bss_transition=1
rrm_neighbor_report=1
rrm_beacon_report=1
