driver=nl80211
interface=wlan1

ssid=Rowe Farm
utf8_ssid=1

country_code=GB
hw_mode=a
ieee80211d=1
uapsd_advertisement_enabled=1

ap_isolate=1
bridge=br0
bridge_hairpin=1
multicast_to_unicast=1
wds_sta=1

ieee80211n=1
ht_capab=[HT40+][HT40-][LDPC][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935]
require_ht=1

ieee80211ac=1
vht_oper_chwidth=1
vht_capab=[RXLDPC][SHORT-GI-80][TX-STBC-2BY1][SU-BEAMFORMER][SU-BEAMFORMEE][MU-BEAMFORMER][MU-BEAMFORMEE][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][SOUNDING-DIMENSION-2][BF-ANTENNA-2][MAX-MPDU-11454][MAX-A-MPDU-LEN-EXP7]

ieee80211ax=1
he_bss_color=17
he_oper_chwidth=1
he_su_beamformer=1
he_su_beamformee=1
he_mu_beamformer=1

bss_transition=1
rrm_neighbor_report=1
rrm_beacon_report=1
