#!/bin/bash

set -o pipefail
export PATH=/bin

start() {
  hostname gl-x3000

  mount -a -t proc
  mount -a -m -t devpts,devtmpfs,sysfs,tmpfs
  mount -m -r -B /run/empty /run/empty
  mkdir -m 1777 -p /run/lock /run/shm

  ln -f -n -s pts/ptmx /dev/ptmx
  ln -f -n -s /proc/self/fd /dev/fd
  ln -f -n -s fd/0 /dev/stdin
  ln -f -n -s fd/1 /dev/stdout
  ln -f -n -s fd/2 /dev/stderr

  echo timer >/sys/class/leds/green:power/trigger

  if ZRAM=$(zramctl -f -s 256M); then
    mkswap $ZRAM >/dev/null
    swapon -d $ZRAM
  fi

  if [[ -c /dev/watchdog ]] && exec >/dev/watchdog && wait; then
    trap 'printf V && exit' TERM
    while printf '\0'; do read -t 5; done
  fi <><(:) & disown

  while read TTY _; do
    daemon -c -r agetty $TTY
  done < /proc/consoles

  ip link set lo up
  ip link set eth0 up
  ip link set eth1 up

  ip link add name br0 type bridge
  ip link set eth0 master br0
  ip link set eth1 master br0
  ip link set br0 up

  ip address add 172.16.0.1/24 dev br0

  syslogd -k
  ssh-keygen -A && $(type -P sshd)

  echo default-on >/sys/class/leds/green:power/trigger

  trap 'exec "$0" stop reboot' INT
  trap 'exec "$0" stop poweroff' TERM

  ctrlaltdel soft
  while true; do read; done <><(:)
}

stop() {
  kill -TERM -1 && sleep 2 && kill -KILL -1
  if umount -a -r; then
    echo "Remounted filesystems read-only"
  else
    sync && echo "Flushed filesystem writes"
  fi
  exec stop "$@"
}

"${@:-start}"
